"""Tactical enrichment model for story-level tactical classification.

Stores per-story tactical classification (ARREST, PROTEST, etc.),
municipality-level coordinates, and intel assessments generated by
the local Haiku tactical agent.
"""
from datetime import datetime
from typing import Optional
from uuid import UUID, uuid4

from sqlalchemy import String, Text, Float, Integer, DateTime, ForeignKey, Index, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class TacticalEnrichment(Base):
    """Per-story tactical classification and municipality-level geolocation."""

    __tablename__ = "tactical_enrichments"

    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid4,
    )
    story_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("stories.id", ondelete="CASCADE"),
        nullable=False, unique=True,
    )

    # Classification
    tactical_type: Mapped[str] = mapped_column(
        String(40), nullable=False,
        comment="SECURITY_DEPLOYMENT|ARREST|PROTEST|ELECTORAL_VIOLENCE|BORDER_INCIDENT|STRIKE|POLITICAL_RALLY|CRIME|CURFEW|RIOT|EXPLOSION|ACCIDENT|OTHER",
    )
    tactical_subtype: Mapped[Optional[str]] = mapped_column(String(60), nullable=True)

    # Municipality-level location
    municipality: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    ward: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    latitude: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    longitude: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Intel assessment
    tactical_context: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    actors: Mapped[Optional[list]] = mapped_column(JSONB, default=list)
    confidence: Mapped[str] = mapped_column(String(10), default="MEDIUM")

    # Metadata
    enriched_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=func.now(), server_default=func.now(),
    )
    model_used: Mapped[str] = mapped_column(String(50), default="haiku")

    # Relationship
    story = relationship("Story", backref="tactical_enrichment")

    __table_args__ = (
        Index("ix_tactical_enrichments_type", "tactical_type"),
        Index("ix_tactical_enrichments_enriched_at", "enriched_at"),
    )

    def __repr__(self) -> str:
        return f"<TacticalEnrichment {self.tactical_type} municipality={self.municipality}>"
